### ISSUE TITLE
Update Kitura-Credentials to 05-03

### ISSUE THREAD

**Issue by AntonAleksandrov** [IBM-Swift/Kitura-Credentials#1]

**Comment by shmuelk** [comment]
We are currently in the midst of the migration to 05-03. We haven't forgotten about Kitura-Credentials. It should be taken care of in the next day or two.

**Comment by shmuelk** [comment]
@AntonAleksandrov:

   - The master branch of Kitura-Credentials supports the 05/03 driver of Swift 3.0.

   - The develop branch of Kitura-Credentials supports the 05/09 driver of Swift 3.0.

Can this issue be closed?

**Comment by AntonAleksandrov** [comment]
@shmuelk yes, this can be closed. Thanks.
