### ISSUE TITLE
Custom redirection

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/Kitura-Credentials#46]
I am using Facebook web login for my app and am using the following authentication flow:

**Welcome page**

I use `credentials.options["failureRedirect"] = "/authentication/welcome"` to redirect unauthenticated request to a welcome page. This is a typical "Please log in with Facebook" page. The `RouterHandler` for this page contains the following code to set up my custom redirection:

```
if let returnAddress = request.session!["returnTo"].string {
    request.session!["originalReturnTo"] = JSON(returnAddress)
}
request.session!["returnTo"] = JSON("http://\(request.hostname):\(request.port)/authentication/signup")
try response.render("welcome", context: [:]).end()
```

This code stores the `returnTo` address and overrides it with the next step in the flow: the sign up page.

**Sign up**

This page checks with the database if the user's Facebook ID is known in the database. If so, the user is redirected to `originalReturnTo` (if available) or to the home page. If not, the (new) user is presented with a sign up page that is pre populated with the information gathered from Facebook.

**Confirmation**

After the (new) user has submitted the sign up page, that user is redirected to a page that stores the user in the database. Finally, the user is redirected to `originalReturnTo` (if available) or to the home page.

As you can see, I had to both read and write the `returnTo` address to set up this flow. Should I worry about this? Is `returnTo` considered part of the API or an implementation detail subject to change? In the latter case: what is the recommended way to achieve the flow above?

**Comment by irar2** [comment]
To make it a part of the API, we can add the following getter and setter to Credentials:

```swift
public func getRedirectingReturnTo(for request: RouterRequest) -> String?

public func setRedirectingReturnTo(_ returnTo: String, for request: RouterRequest)
```

@youming-lin What do you think?
