### ISSUE TITLE
Dropbox sign-in-- of interest?

### ISSUE THREAD

**Issue by crspybits** [IBM-Swift/Kitura-Credentials#58]
I'm not sure if this of interest for your list as it's not a general purpose sign-in. Rather it's of use if the server app is making use of Dropbox cloud storage. 
https://github.com/crspybits/CredentialsDropbox.git

**Comment by ianpartridge** [comment]
Thanks!  I've added this to https://www.kitura.io/en/api/ 👍

**Comment by crspybits** [comment]
I see that that link above is no longer working...

**Comment by ianpartridge** [comment]
Ah yes our new packages page is at https://www.kitura.io/packages.html but currently it doesn't feature community-authored packages. I'll get that fixed.

**Comment by crspybits** [comment]
Thank you!
