### ISSUE TITLE
Concern about caching access tokens

### ISSUE THREAD

**Issue by crspybits** [IBM-Swift/Kitura-Credentials#75]
As I understand it, each of the "Token" type credentials plugins uses the `usersCache` before it tries to authenticate with a network based method. So, if an access token has been authenticated before, while the server has been launched, and the access token hasn't been evicted from the cache due to memory pressure, the access token will still be cached, and the user will authenticate without a network request. What happens then if the access token has expired (e.g., due to Google, or Facebook policies) or a user has explicitly revoked the token? As I understand it, the access token would continue to be considered valid by credentials plugins until either (a) the server reboots, or (b) the cache gets full and the access token has to be evicted. Does that sound right? 

I'm wondering if there should be client-control over caching policies. E.g., to enable a time-based eviction of access tokens, so they might necessarily get evicted periodically. 

Thanks.

**Comment by Andrew-Lees11** [comment]
@crspybits 
Your description does sum up the current behavior of credentials. The tokens are cached and linked to a profile that is used for future requests. I will now look into possible method for invalidating tokens either through allowing you to manually clear the cache or having a timeout for how long a profile is valid for.

**Comment by crspybits** [comment]
@Andrew-Lees11 Sounds good. Thanks for the update. I'm expecting for my purposes that a timeout that I could set duration of would be most useful. Not sure about other use cases though.

**Comment by Andrew-Lees11** [comment]
@crspybits 
I know it's not quite what what you are after but did you realise you do have control to change the credentials cache? For example, using our [Facebook plugin](https://github.com/IBM-Swift/Kitura-CredentialsFacebook), you could clear the whole cache as follows:
```swift
let fbCreds = CredentialsFacebook(clientId: "Id", clientSecret: "secret", callbackUrl: "url", options: [])
fbCreds.usersCache?.removeAllObjects()
```
This would let you reset all tokens without restarting your server. You can also set the max cache size, remove individual tokens or map through the elements. 
There is not a time based eviction policy though which as I understand it is what you are after.

**Comment by crspybits** [comment]
@Andrew-Lees11 I think the way I'd have to work with that is to periodically do this flushing. E.g., say every 60 minutes. With that I'd have some access tokens that were 60 minutes old and some that were, say, 1 minute old. Probably it would work OK. Better than nothing.

**Comment by Andrew-Lees11** [comment]
@crspybits I have raised a fairly simple [PR](https://github.com/IBM-Swift/Kitura-Credentials/pull/78) that adds the time the cache element was created at to the baseCacheElement.
 This can then be accessed either by the user or by a credentials plugin to invalidate cached tokens that are older than a certain date. 
Implementing an automatic eviction process would need to be implemented in the plugins so I will look into that now. Do you have a particular plugin you are using since I'll raise the PR against that first.

**Comment by crspybits** [comment]
@Andrew-Lees11 I'm using CredentialsGoogleToken and CredentialsFacebookToken. When you've got these changes done, I'll also add them into CredentialsDropboxToken, one that I've contributed. Thanks!

**Comment by Andrew-Lees11** [comment]
I have raised a [PR](https://github.com/IBM-Swift/Kitura-CredentialsGoogle/pull/37) with a suggested implementation to CredentialsGoogle. We could then roll this out to the other plugins.

**Comment by Andrew-Lees11** [comment]
I'm closing this since the PR adding a timestamp to the cache has been merged and tagged and The plugins have been updated with a TokenTimeToLive that will reject a cached token after the specified time.
